import Link from "next/link";
import { createCommentAction, deleteCommentAction, editCommentAction, reportCommentAction, voteCommentAction } from "@/app/autos/[slug]/comment-actions";

export type PublicComment = { id:string;parent_id:string|null;author_id:string;body:string;status:string;created_at:string;updated_at:string;author_username:string|null;is_seller:boolean;vote_count:number;viewer_voted:boolean };

export function ListingComments({listingId,comments,viewerId}:{listingId:string;comments:PublicComment[];viewerId:string|null}){
 const roots=comments.filter(c=>!c.parent_id);
 return <section className="border-t public-rule py-10" id="comentarios"><div className="flex items-end justify-between"><div><p className="editorial-kicker">Conversation</p><h2 className="mt-2 text-xl font-bold text-white">Comentarios</h2></div><span className="text-xs text-zinc-600">{comments.filter(c=>c.status==="published").length}</span></div>
 {viewerId?<form action={createCommentAction.bind(null,listingId,null)} className="mt-6"><label className="sr-only" htmlFor="new-comment">Agregar comentario</label><textarea id="new-comment" name="body" required maxLength={2000} placeholder="Pregunta o aporta información sobre este auto…" className="public-field min-h-24 w-full resize-y p-3 text-sm"/><button className="mt-2 bg-orange-600 px-4 py-2 text-xs font-bold text-white">Publicar comentario</button></form>:<p className="mt-6 border public-rule p-4 text-sm text-zinc-500"><Link href={`/login?next=%2Fautos%2F${listingId}%23comentarios`} className="font-semibold text-orange-400">Ingresa</Link> para participar en la conversación.</p>}
 <div className="mt-8 space-y-6">{roots.length?roots.map(c=><CommentNode key={c.id} comment={c} all={comments} listingId={listingId} viewerId={viewerId} depth={0}/>):<p className="text-sm text-zinc-600">Todavía no hay comentarios.</p>}</div></section>;
}

function CommentNode({comment,all,listingId,viewerId,depth}:{comment:PublicComment;all:PublicComment[];listingId:string;viewerId:string|null;depth:number}){
 const replies=all.filter(c=>c.parent_id===comment.id); const removed=comment.status==="removed";
 return <article className={`${depth?"border-l public-rule pl-4":""}`} style={{marginLeft:`${Math.min(depth,3)*0.5}rem`}}><div className="flex flex-wrap items-center gap-2 text-xs"><strong className="text-zinc-200">@{comment.author_username??"usuario"}</strong>{comment.is_seller?<span className="rounded-full bg-emerald-950 px-2 py-0.5 text-[8px] font-bold uppercase tracking-wider text-emerald-200">Vendedor</span>:null}<time className="text-zinc-600">{new Intl.DateTimeFormat("es-MX",{dateStyle:"medium"}).format(new Date(comment.created_at))}</time>{comment.updated_at!==comment.created_at&&!removed?<span className="text-zinc-700">editado</span>:null}</div><p className={`mt-2 whitespace-pre-wrap text-sm leading-6 ${removed?"italic text-zinc-600":"text-zinc-400"}`}>{comment.body}</p>
 {!removed?<div className="mt-3 flex flex-wrap items-center gap-4 text-[11px] text-zinc-500">{viewerId?<form action={voteCommentAction.bind(null,listingId,comment.id)}><button aria-label={`Votar comentario de ${comment.author_username??"usuario"}`} className={comment.viewer_voted?"text-orange-400":"hover:text-white"}>↑ {comment.vote_count}</button></form>:<span>↑ {comment.vote_count}</span>}{viewerId?<details><summary className="cursor-pointer hover:text-white">Responder</summary><form action={createCommentAction.bind(null,listingId,comment.id)} className="mt-2 flex min-w-64 gap-2"><input name="body" required maxLength={2000} className="public-field min-w-0 flex-1 px-2 py-1"/><button className="text-orange-400">Enviar</button></form></details>:null}{viewerId===comment.author_id?<><details><summary className="cursor-pointer">Editar</summary><form action={editCommentAction.bind(null,listingId,comment.id)} className="mt-2 flex min-w-64 gap-2"><input name="body" defaultValue={comment.body} required maxLength={2000} className="public-field min-w-0 flex-1 px-2 py-1"/><button>Guardar</button></form></details><form action={deleteCommentAction.bind(null,listingId,comment.id)}><button className="hover:text-red-400">Eliminar</button></form></>:null}{viewerId&&viewerId!==comment.author_id?<details><summary className="cursor-pointer">••• Denunciar</summary><form action={reportCommentAction.bind(null,listingId,comment.id)} className="mt-2 grid min-w-64 gap-2"><select name="reason" className="public-field p-2"><option value="spam">Spam</option><option value="harassment">Acoso</option><option value="false_information">Información falsa</option><option value="personal_information">Información personal</option><option value="inappropriate">Inapropiado</option><option value="other">Otro</option></select><input name="details" maxLength={1000} placeholder="Detalle opcional" className="public-field p-2"/><button className="text-left text-orange-400">Enviar denuncia</button></form></details>:null}</div>:null}
 {replies.length?<div className="mt-5 space-y-5">{replies.map(r=><CommentNode key={r.id} comment={r} all={all} listingId={listingId} viewerId={viewerId} depth={depth+1}/>)}</div>:null}</article>;
}
