import { saveRichListingAction } from "@/app/cuenta/anuncios/rich-actions";

const field="mt-2 min-h-11 w-full border bg-white px-3 py-2 text-sm";
const statusOptions=["unknown","yes","no","not_applicable"];
export function RichListingForm({listingId,data}:{listingId:string;data:Record<string,unknown>}){
 const ownership=(data.ownership??{}) as Record<string,unknown>;const documentation=(data.documentation??{}) as Record<string,unknown>;
 const lines=(key:string,formatter:(item:Record<string,unknown>)=>string)=>(data[key] as Record<string,unknown>[]??[]).map(formatter).join("\n");
 return <form action={saveRichListingAction.bind(null,listingId)} className="mt-12 border-t pt-10"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-accent">Ficha enriquecida</p><h2 className="mt-2 text-2xl font-black">Estado, historial y contenido adicional</h2><p className="mt-2 text-sm text-stone-600">Estas secciones son opcionales y se guardan separadas de los datos básicos.</p></div>
 <div className="mt-8 space-y-4">
 <details open className="border p-5"><summary className="cursor-pointer font-black">Estado y documentación</summary><div className="mt-5 grid gap-4 sm:grid-cols-2"><label>VIN/NIV<input name="vin" defaultValue={String(ownership.vin??"")} maxLength={17} className={field}/></label><label>Originalidad<select name="originality_status" defaultValue={String(ownership.originality_status??"unknown")} className={field}><option value="unknown">Sin especificar</option><option value="original">Original</option><option value="mostly_original">Mayormente original</option><option value="modified">Modificado</option><option value="heavily_modified">Muy modificado</option></select></label><label>Tipo de documento<select name="document_type" defaultValue={String(documentation.document_type??"")} className={field}><option value="">Sin especificar</option>{["original_invoice","refactura","dealer_invoice","insurance_invoice","import_pedimento","foreign_title","antique_vehicle","other"].map(x=><option key={x}>{x}</option>)}</select></label><label>Número de llaves<input name="keys_count" type="number" min="0" max="10" defaultValue={String(documentation.keys_count??"")} className={field}/></label>{[["taxes_current","Tenencias"],["registration_card","Tarjeta de circulación"],["emissions_status","Verificación"],["insurance_current","Seguro"],["owners_manual","Manual"]].map(([name,label])=><label key={name}>{label}<select name={name} defaultValue={String(documentation[name]??"unknown")} className={field}>{statusOptions.map(x=><option key={x}>{x}</option>)}</select></label>)}<label>Historial de servicio<select name="service_history_level" defaultValue={String(documentation.service_history_level??"unknown")} className={field}>{["unknown","complete","partial","none"].map(x=><option key={x}>{x}</option>)}</select></label></div></details>
 <details className="border p-5"><summary className="cursor-pointer font-black">Ownership e historia de servicio</summary><div className="mt-5 grid gap-4 sm:grid-cols-3"><label>Mes desde<input name="owned_since_month" type="number" min="1" max="12" defaultValue={String(ownership.owned_since_month??"")} className={field}/></label><label>Inicio de ownership · YYYY<input name="owned_since_year" type="number" min="1886" max={new Date().getFullYear()} defaultValue={String(ownership.owned_since_year??"")} className={field}/></label><label>Propietarios conocidos<select name="known_owner_count" defaultValue={String(ownership.known_owner_count??"unknown")} className={field}>{["unknown","1","2","3","4+"].map(x=><option key={x}>{x}</option>)}</select></label><label className="sm:col-span-3">Notas de ownership<textarea name="ownership_notes" defaultValue={String(ownership.ownership_notes??"")} className={`${field} min-h-24`}/></label><label className="sm:col-span-3">Servicios — fecha | km | descripción | yes/no<textarea name="services" defaultValue={lines("serviceRecords",x=>`${x.service_date??""} | ${x.mileage_km??""} | ${x.description??""} | ${x.document_available?"yes":"no"}`)} className={`${field} min-h-32 font-mono`}/></label></div></details>
 <details className="border p-5"><summary className="cursor-pointer font-black">Equipment, modificaciones y flaws</summary><div className="mt-5 grid gap-5"><label>Equipment — un elemento por línea<textarea name="equipment" defaultValue={lines("equipment",x=>String(x.name))} className={`${field} min-h-28`}/></label><label>Mods estructuradas — tipo | nombre | descripción<textarea name="modifications" defaultValue={lines("modifications",x=>`${x.category} | ${x.name} | ${x.description??""}`)} className={`${field} min-h-28 font-mono`}/></label><label>Flaws — tipo | título | descripción | photo UUID opcional<textarea name="flaws" defaultValue={lines("flaws",x=>`${x.category} | ${x.title} | ${x.description} | ${x.photo_id??""}`)} className={`${field} min-h-28 font-mono`}/></label><label>Incluido con la venta — nombre | descripción<textarea name="included" defaultValue={lines("includedItems",x=>`${x.name} | ${x.description??""}`)} className={`${field} min-h-28`}/></label></div></details>
 <details className="border p-5"><summary className="cursor-pointer font-black">Video</summary><label className="mt-5 block">Hasta 3 videos — tipo | URL de YouTube o Vimeo<textarea name="videos" defaultValue={lines("videos",x=>`${x.type} | ${x.external_url}`)} className={`${field} min-h-28 font-mono`}/></label><p className="mt-2 text-xs text-stone-500">Tipos: walkaround, cold_start, engine_running, driving, exhaust, interior, other.</p></details>
 </div><button className="mt-6 min-h-11 bg-stone-950 px-5 py-3 text-sm font-bold text-white hover:bg-accent">Guardar ficha enriquecida</button></form>;
}
