import { FlawPhotoLink } from "@/components/flaw-photo-link";

export type RichListingData = {
  ownership: null | { ownedSinceMonth: number | null; ownedSinceYear: number | null; knownOwnerCount: string; ownershipNotes: string | null; originalityStatus: string; vinMasked: string | null };
  documentation: null | Record<string, string | number | boolean | null>;
  equipment: Array<{ id: string; name: string; category: string | null }>;
  modifications: Array<{ id: string; category: string; name: string; description: string | null }>;
  flaws: Array<{ id: string; category: string; title: string; description: string; photo_id: string | null }>;
  serviceRecords: Array<{ id: string; service_date: string | null; mileage_km: number | null; description: string; document_available: boolean }>;
  includedItems: Array<{ id: string; name: string; description: string | null }>;
  videos: Array<{ id: string; type: string; external_url: string | null; duration_seconds: number | null }>;
};

const months = ["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"];
const originality: Record<string,string> = { original:"Original",mostly_original:"Mayormente original",modified:"Modificado",heavily_modified:"Muy modificado" };
const docType: Record<string,string> = { original_invoice:"Factura original",refactura:"Refactura",dealer_invoice:"Factura de agencia",insurance_invoice:"Factura de aseguradora",import_pedimento:"Pedimento de importación",foreign_title:"Título extranjero",antique_vehicle:"Documentación de auto antiguo",other:"Otra documentación" };

function Block({ kicker, children }: { kicker: string; children: React.ReactNode }) { return <section className="border-t public-rule py-9"><h2 className="editorial-kicker">{kicker}</h2><div className="mt-5">{children}</div></section>; }
function videoEmbed(url: string) { try { const u=new URL(url); if(u.hostname.includes("youtu.be")) return `https://www.youtube-nocookie.com/embed/${u.pathname.slice(1)}`; if(u.hostname.includes("youtube.com")) return `https://www.youtube-nocookie.com/embed/${u.searchParams.get("v") ?? ""}`; if(u.hostname.includes("vimeo.com")) return `https://player.vimeo.com/video/${u.pathname.split("/").filter(Boolean).at(-1)}`; } catch {} return null; }

export function RichListingSections({ rich, mileageKm, transmission }: { rich: RichListingData; mileageKm: number | null; transmission: string | null }) {
  const highlights = [transmission, mileageKm === null ? null : `${new Intl.NumberFormat("es-MX").format(mileageKm)} km`, rich.documentation?.document_type ? docType[String(rich.documentation.document_type)] : null, rich.ownership?.ownedSinceYear ? `Propietario actual desde ${rich.ownership.ownedSinceYear}` : null, rich.ownership?.originalityStatus && rich.ownership.originalityStatus !== "unknown" ? originality[rich.ownership.originalityStatus] : null, rich.documentation?.service_history_level === "complete" ? "Historial de servicio completo" : rich.documentation?.service_history_level === "partial" ? "Historial de servicio parcial" : null].filter(Boolean) as string[];
  const docBadges = [rich.documentation?.document_type ? docType[String(rich.documentation.document_type)] : null, Number(rich.documentation?.keys_count) > 0 ? `${rich.documentation?.keys_count} ${Number(rich.documentation?.keys_count)===1?"llave":"llaves"}` : null, rich.documentation?.owners_manual === "yes" ? "Manual" : null, rich.documentation?.insurance_current === "yes" ? "Seguro vigente" : null, rich.documentation?.taxes_current === "yes" ? "Tenencias al corriente" : null, rich.documentation?.service_history_level === "complete" ? "Servicios documentados" : rich.documentation?.service_history_level === "partial" ? "Historial parcial" : null].filter(Boolean) as string[];
  return <div>
    {highlights.length ? <Block kicker="Highlights"><ul className="grid gap-2 sm:grid-cols-2">{highlights.map((item)=><li key={item} className="border-l-2 border-orange-500 pl-3 text-sm font-semibold text-zinc-200">{item}</li>)}</ul></Block> : null}
    {rich.equipment.length ? <Block kicker="Equipment"><ul className="grid gap-x-8 gap-y-2 text-sm text-zinc-400 sm:grid-cols-2">{rich.equipment.map((item)=><li key={item.id}>• {item.name}</li>)}</ul></Block> : null}
    {rich.modifications.length ? <Block kicker="Modifications"><div className="grid gap-5 sm:grid-cols-2">{rich.modifications.map((item)=><article key={item.id}><p className="text-[10px] font-bold uppercase tracking-wider text-orange-500">{item.category}</p><h3 className="mt-1 font-semibold text-zinc-200">{item.name}</h3>{item.description?<p className="mt-1 text-sm leading-6 text-zinc-500">{item.description}</p>:null}</article>)}</div></Block> : null}
    {rich.flaws.length ? <Block kicker="Known flaws"><div className="grid gap-5 sm:grid-cols-2">{rich.flaws.map((item)=><article key={item.id} className="border-l public-rule pl-4"><h3 className="font-semibold text-zinc-200">{item.title}</h3><p className="mt-1 text-sm leading-6 text-zinc-500">{item.description}</p>{item.photo_id?<FlawPhotoLink photoId={item.photo_id}/>:null}</article>)}</div></Block> : null}
    {rich.serviceRecords.length ? <Block kicker="Service history"><ol className="space-y-5">{rich.serviceRecords.map((item)=><li key={item.id} className="grid gap-1 sm:grid-cols-[11rem_1fr]"><p className="text-xs text-zinc-500">{item.service_date ? new Intl.DateTimeFormat("es-MX",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(item.service_date)) : "Fecha no indicada"}{item.mileage_km!==null?` · ${new Intl.NumberFormat("es-MX").format(item.mileage_km)} km`:""}</p><div><p className="text-sm text-zinc-300">{item.description}</p>{item.document_available?<span className="mt-1 inline-flex text-[10px] font-bold uppercase text-[var(--driven-green)]">Comprobante disponible</span>:null}</div></li>)}</ol></Block> : null}
    {rich.ownership ? <Block kicker="Ownership"><div className="grid gap-3 text-sm text-zinc-400 sm:grid-cols-2">{rich.ownership.ownedSinceYear?<p>Con el propietario actual desde {rich.ownership.ownedSinceMonth?`${months[rich.ownership.ownedSinceMonth-1]} de `:""}{rich.ownership.ownedSinceYear}</p>:null}{rich.ownership.knownOwnerCount!=="unknown"?<p>{rich.ownership.knownOwnerCount} propietarios conocidos</p>:null}{rich.ownership.vinMasked?<p className="font-mono">VIN/NIV {rich.ownership.vinMasked}</p>:null}{rich.ownership.ownershipNotes?<p className="sm:col-span-2">{rich.ownership.ownershipNotes}</p>:null}</div></Block> : null}
    {docBadges.length ? <Block kicker="Documentation"><div className="flex flex-wrap gap-2">{docBadges.map((badge)=><span key={badge} className="rounded-full border public-rule px-3 py-1.5 text-xs text-zinc-300">{badge}</span>)}</div></Block> : null}
    {rich.includedItems.length ? <Block kicker="Included with sale"><ul className="grid gap-3 sm:grid-cols-2">{rich.includedItems.map((item)=><li key={item.id}><p className="text-sm font-semibold text-zinc-300">{item.name}</p>{item.description?<p className="text-xs text-zinc-500">{item.description}</p>:null}</li>)}</ul></Block> : null}
    {rich.videos.length ? <Block kicker="Videos"><div className="grid gap-4 sm:grid-cols-2">{rich.videos.map((video)=>{const embed=video.external_url?videoEmbed(video.external_url):null; return embed?<iframe key={video.id} src={embed} title={`Video ${video.type}`} loading="lazy" allow="fullscreen; picture-in-picture" className="aspect-video w-full rounded-sm border public-rule"/>:null;})}</div></Block> : null}
  </div>;
}
